name: CI

on: [push, pull_request]

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] #, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v5
      with:
        submodules: recursive

    - name: Install LilyPond on Linux
      run: |
        wget --no-verbose https://gitlab.com/lilypond/lilypond/-/releases/v2.24.0/downloads/lilypond-2.24.0-linux-x86_64.tar.gz
        tar -xf lilypond-2.24.0-linux-x86_64.tar.gz
        echo "$(pwd)/lilypond-2.24.0/bin" >> $GITHUB_PATH
      if: ${{ matrix.os == 'ubuntu-latest' }}
    - name: Install LilyPond on macOS
      run: |
        brew update
        brew install lilypond
      if: ${{ matrix.os == 'macos-latest' }}
    - name: Install LilyPond on Windows
      run: |
        choco install lilypond --no-progress
        Add-Content $Env:GITHUB_PATH "${Env:ProgramFiles(x86)}\LilyPond\usr\bin" -Encoding utf8
      if: ${{ matrix.os == 'windows-latest' }}

    - name: Create PDFs with ASCII filenames
      run: |
        lilypond --output='Bach - Gavotte in G Minor' bach-bwv-808/horn.ly
        lilypond --output='Bach - Sinfonia from Cantata 156' bach-bwv-156-1/horn.ly
        lilypond --output='Franz - 30 Exercises for Horn' franz-30-exercises-for-horn/main.ly
        lilypond --output='Kopprasch - Op. 6 - 60 Studies for Low Horn' kopprasch-opus-6-60-studies-for-low-horn/main.ly
        lilypond --output='Maxime-Alphonse - 200 New Studies, Vol. 1' maxime-alphonse-200-studies-1/main.ly
        lilypond --output='Maxime-Alphonse - 200 New Studies, Vol. 2' maxime-alphonse-200-studies-2/main.ly
        lilypond --output='Maxime-Alphonse - 200 New Studies, Vol. 3' maxime-alphonse-200-studies-3/main.ly
        lilypond --output='Mozart - Horn Concerto No. 1' mozart-k-412-concerto-1/horn.ly
        lilypond --output='Reinecke - Op. 188 - Trio for Piano, Oboe, and Horn' reinecke-opus-188-trio/horn.ly
        lilypond --output='Schumann - Op. 70 - Adagio and Allegro' schumann-opus-70-adagio-and-allegro/horn.ly
        lilypond --output='Strauss, Franz - Op. 7 - Nocturno' strauss-franz-opus-7-nocturno/horn.ly
        lilypond --output='Strauss, Richard - Op. 11 - Horn Concerto No. 1' strauss-richard-opus-11-concerto-1/horn.ly
    - name: Create PDFs with UTF-8 filenames on Linux and macOS
      run: |
        lilypond --output='Bach - Aria (“Lass, o Fürst”)' bach-bwv-130-5/horn.ly
        lilypond --output='Bonis - Scènes de la Forêt' bonis-opus-123-scenes-de-la-foret/horn.ly
        lilypond --output='Glazunov - Op. 24 - Rêverie' glazunov-opus-24-reverie/horn.ly
        lilypond --output='Kling - 40 Characteristic Études for Horn' kling-40-characteristic-etudes/main.ly
        lilypond --output='Saint-Saëns - Op. 36 - Romance' saint-saens-opus-36-romance/horn.ly
        lilypond --output='Saint-Saëns - Op. 36 - Romance - Piano' saint-saens-opus-36-romance/piano.ly
        lilypond --output='Saint-Saëns - Op. 94 - Morceau de Concert' saint-saens-opus-94-morceau-de-concert/horn.ly
        lilypond --output='Saint-Saëns - The Swan' saint-saens-swan/horn.ly
      if: ${{ matrix.os != 'windows-latest' }}
    - name: Create PDFs with UTF-8 filenames on Windows
      run: |
        lilypond bach-bwv-130-5\horn.ly; Rename-Item horn.pdf 'Bach - Aria (“Lass, o Fürst”)'
        lilypond bonis-opus-123-scenes-de-la-foret\horn.ly; Rename-Item horn.pdf 'Bonis - Scènes de la Forêt.pdf'
        lilypond glazunov-opus-24-reverie\horn.ly; Rename-Item horn.pdf 'Glazunov - Op. 24 - Rêverie.pdf'
        lilypond kling-40-characteristic-etudes\main.ly; Rename-Item main.pdf 'Kling - 40 Characteristic Études for Horn.pdf'
        lilypond saint-saens-opus-36-romance\horn.ly; Rename-Item horn.pdf 'Saint-Saëns - Op. 36 - Romance.pdf'
        lilypond saint-saens-opus-94-morceau-de-concert\horn.ly; Rename-Item horn.pdf 'Saint-Saëns - Op. 94 - Morceau de Concert.pdf'
        lilypond saint-saens-swan\horn.ly; Rename-Item horn.pdf 'Saint-Saëns - The Swan.pdf'
      if: ${{ matrix.os == 'windows-latest' }}

    - name: Archive PDFs
      uses: actions/upload-artifact@main
      with:
        name: ${{ runner.os }} artifacts
        path: '*.pdf'
