name: CI

on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install LilyPond
      run: |
        wget --no-verbose https://lilypond.org/download/binaries/linux-64/lilypond-2.22.0-1.linux-64.sh
        sudo sh lilypond-2.22.0-1.linux-64.sh --batch

    - name: Install fonts
      run: |
        wget --no-verbose --output-document='Playfair Display.zip' 'https://fonts.google.com/download?family=Playfair%20Display'
        mkdir -p ~/.fonts
        unzip -j 'Playfair Display.zip' 'static/*.ttf' -d ~/.fonts

    - name: Create PDFs
      run: |
        lilypond --output='Glazunov - Op. 24 - Rêverie' glazunov-opus-24-reverie/horn.ly
        lilypond --output='Kling - 40 Characteristic Études for Horn' kling-40-characteristic-etudes/main.ly
        lilypond --output='Kopprasch - Op. 6 - 60 Studies for Low Horn' kopprasch-opus-6-60-studies-for-low-horn/main.ly
        lilypond --output='Reinecke - Op. 188 - Trio for Piano, Oboe, and Horn' reinecke-opus-188-trio/horn.ly
        lilypond --output='Saint-Saëns - Op. 36 - Romance' saint-saens-opus-36-romance/horn.ly
        lilypond --output='Saint-Saëns - Op. 94 - Morceau de Concert' saint-saens-opus-94-morceau-de-concert/horn.ly
        lilypond --output='Saint-Saëns - The Swan' saint-saens-swan/horn.ly
        lilypond --output='Schumann - Op. 70 - Adagio and Allegro' schumann-opus-70-adagio-and-allegro/horn.ly
        lilypond --output='Strauss, Franz - Op. 7 - Nocturno' strauss-franz-opus-7-nocturno/horn.ly
        lilypond --output='Strauss, Richard - Op. 11 - Horn Concerto No. 1' strauss-richard-opus-11-concerto-1/horn.ly

    - name: Archive PDFs
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }} artifacts
        path: '*.pdf'

  macOS:
    runs-on: macos-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Update Homebrew
      run: brew update

    - name: Install LilyPond
      run: |
        brew install --cask mactex-no-gui
        brew tap nwhetsell/lilypond
        brew install lilypond

    - name: Install fonts
      run: |
        brew tap homebrew/cask-fonts
        brew install font-playfair-display

    - name: Create PDFs
      run: |
        lilypond --output='Glazunov - Op. 24 - Rêverie' glazunov-opus-24-reverie/horn.ly
        lilypond --output='Kling - 40 Characteristic Études for Horn' kling-40-characteristic-etudes/main.ly
        lilypond --output='Kopprasch - Op. 6 - 60 Studies for Low Horn' kopprasch-opus-6-60-studies-for-low-horn/main.ly
        lilypond --output='Reinecke - Op. 188 - Trio for Piano, Oboe, and Horn' reinecke-opus-188-trio/horn.ly
        lilypond --output='Saint-Saëns - Op. 36 - Romance' saint-saens-opus-36-romance/horn.ly
        lilypond --output='Saint-Saëns - Op. 94 - Morceau de Concert' saint-saens-opus-94-morceau-de-concert/horn.ly
        lilypond --output='Saint-Saëns - The Swan' saint-saens-swan/horn.ly
        lilypond --output='Schumann - Op. 70 - Adagio and Allegro' schumann-opus-70-adagio-and-allegro/horn.ly
        lilypond --output='Strauss, Franz - Op. 7 - Nocturno' strauss-franz-opus-7-nocturno/horn.ly
        lilypond --output='Strauss, Richard - Op. 11 - Horn Concerto No. 1' strauss-richard-opus-11-concerto-1/horn.ly

    - name: Archive PDFs
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }} artifacts
        path: '*.pdf'

  Windows:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install LilyPond
      run: |
        choco install lilypond --no-progress
        Add-Content $Env:GITHUB_PATH "${Env:ProgramFiles(x86)}\LilyPond\usr\bin" -Encoding utf8

    - name: Install fonts
      run: |
        curl.exe --output 'Playfair Display.zip' --show-error --silent https://fonts.google.com/download?family=Playfair%20Display
        7z e -o"$([Environment]::GetFolderPath('Fonts'))" 'Playfair Display.zip' static\*.ttf
        New-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts' 'Playfair Display Medium' -Value PlayfairDisplay-Medium.ttf
        New-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts' 'Playfair Display Regular' -Value PlayfairDisplay-Regular.ttf

    - name: Create PDFs
      run: |
        lilypond glazunov-opus-24-reverie\horn.ly; Rename-Item horn.pdf 'Glazunov - Op. 24 - Rêverie.pdf'
        lilypond kling-40-characteristic-etudes\main.ly; Rename-Item main.pdf 'Kling - 40 Characteristic Études for Horn.pdf'
        lilypond --output='Kopprasch - Op. 6 - 60 Studies for Low Horn' kopprasch-opus-6-60-studies-for-low-horn\main.ly
        lilypond --output='Reinecke - Op. 188 - Trio for Piano, Oboe, and Horn' reinecke-opus-188-trio\horn.ly
        lilypond saint-saens-opus-36-romance\horn.ly; Rename-Item horn.pdf 'Saint-Saëns - Op. 36 - Romance.pdf'
        lilypond saint-saens-opus-94-morceau-de-concert\horn.ly; Rename-Item horn.pdf 'Saint-Saëns - Op. 94 - Morceau de Concert.pdf'
        lilypond saint-saens-swan\horn.ly; Rename-Item horn.pdf 'Saint-Saëns - The Swan.pdf'
        lilypond --output='Schumann - Op. 70 - Adagio and Allegro' schumann-opus-70-adagio-and-allegro\horn.ly
        lilypond --output='Strauss, Franz - Op. 7 - Nocturno' strauss-franz-opus-7-nocturno\horn.ly
        lilypond --output='Strauss, Richard - Op. 11 - Horn Concerto No. 1' strauss-richard-opus-11-concerto-1\horn.ly

    - name: Archive PDFs
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }} artifacts
        path: '*.pdf'
